import "./globals.css";
import { AuthContextProvider } from '@/context/auth/authContext'
import { DataContextProvider } from "@/context/data/dataContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-full h-screen flex">
          <div className="w-full space-y-8 flex">
            <AuthContextProvider>
                  {children}
            </AuthContextProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
